repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.278
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        exclude: ^data_integration/(.)*hooks.py
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt

