---
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_CI_COMMIT_TAG}",
        ".",
      ]

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_CI_COMMIT_TAG}"
options:
  dynamic_substitutions: true
