[tool.poetry]
name = "kubernetes etc"
version = "0.1.0"
description = ""
authors = ["Yannik Sacherer <yannik@sacherer.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.7"
fastapi = {extras = ["standard"], version = "^0.115.12"}
pyiceberg = {extras = ["gcsfs"], version = "^0.9.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
